export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: 'user' | 'admin' | 'super_admin';
}

export interface Project {
  id: string;
  name: string;
  description: string;
  status: 'draft' | 'processing' | 'completed' | 'failed';
  settings: Record<string, any>;
  metadata: Record<string, any>;
  createdAt: string;
  updatedAt: string;
  rooms?: Room[];
}

export interface Room {
  id: string;
  projectId: string;
  name: string;
  description: string;
  position?: {
    x: number;
    y: number;
    z: number;
  };
  rotation?: {
    x: number;
    y: number;
    z: number;
  };
  status: 'pending' | 'processing' | 'completed' | 'failed';
  metadata?: Record<string, any>;
  images?: Image[];
  hotspots?: Hotspot[];
}

export interface Image {
  id: string;
  roomId: string;
  filename: string;
  originalFilename: string;
  mimeType: string;
  fileSize: number;
  storagePath: string;
  metadata?: {
    gyro?: {
      x: number;
      y: number;
      z: number;
    };
    compass?: number;
    timestamp?: number;
  };
  processingStatus?: {
    uploaded: boolean;
    processed: boolean;
    stitched: boolean;
  };
  createdAt: string;
}

export interface Hotspot {
  id: string;
  roomId: string;
  targetRoomId?: string;
  type: 'navigation' | 'info' | 'measurement';
  position: {
    x: number;
    y: number;
    z: number;
  };
  rotation?: {
    x: number;
    y: number;
    z: number;
  };
  title?: string;
  description?: string;
  data?: Record<string, any>;
  isAutoGenerated: boolean;
  createdAt: string;
}

export interface Annotation {
  id: string;
  roomId: string;
  type: 'point' | 'polygon' | 'line';
  coordinates: Array<{
    x: number;
    y: number;
    z: number;
  }>;
  title?: string;
  description?: string;
  style?: Record<string, any>;
  createdAt: string;
}

export interface Measurement {
  id: string;
  roomId: string;
  type: 'point_to_point' | 'corner' | 'edge';
  points: Array<{
    x: number;
    y: number;
    z: number;
  }>;
  distance?: number;
  unit: string;
  label?: string;
  metadata?: Record<string, any>;
  createdAt: string;
}
